import type { School } from '@/types/school';
import { calcOverallScore } from './scoring';

const sampleSchools: Omit<School, 'overallScore' | 'rank'>[] = [
  {
    id: 'techcamp',
    name: 'テックキャンプ',
    slug: 'techcamp',
    logo: { url: '/images/schools/techcamp.svg', width: 200, height: 56 },
    officialUrl: 'https://tech-camp.in',
    affiliateUrl: 'https://example.com/aff/techcamp',
    catchphrase: '転職成功率98%、業界最大級の転職保証',
    description: '未経験から最短10週間でエンジニア転職を実現。専属メンターと転職サポートで転職率98%を達成。',
    price: {
      basePrice: 680000,
      maxPrice: 800000,
      hasInstallment: true,
      installmentMonths: 24,
      installmentFeeRate: 0.15,
      subsidyAvailable: true,
    },
    curriculum: {
      languages: ['Ruby', 'JavaScript', 'HTML', 'CSS'],
      frameworks: ['Ruby on Rails', 'React'],
      hasPortfolio: true,
      weeklyHours: 60,
      totalHours: 600,
      hasMentor: true,
    },
    support: {
      jobSupport: true,
      jobSupportDetail: '転職保証付き（条件あり）、専任のキャリアアドバイザーが内定まで伴走',
      mentorResponse: '15分以内',
      communityExists: true,
      supportHours: '毎日10:00〜22:00',
    },
    results: {
      jobChangeRate: 98,
      satisfactionRate: 95,
      graduatesCount: 40000,
    },
    format: ['online', 'offline'],
    purpose: ['career'],
    targetLevel: ['beginner'],
    freeTrial: true,
    freeTrialDetail: '無料カウンセリング・体験あり',
    pros: [
      '転職保証制度（条件付き）',
      '専属メンターによる手厚いサポート',
      '卒業生コミュニティが活発',
      '実践的なポートフォリオ制作',
    ],
    cons: [
      '料金が高め（68万円〜）',
      '短期集中型で自己学習ペース不可',
      'Webエンジニア特化（他職種には不向き）',
    ],
    reviewScore: { curriculum: 4.4, price: 3.2, support: 4.5, userReview: 4.1 },
    reviewCount: 342,
    publishedAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2026-01-15T00:00:00.000Z',
  },
  {
    id: 'dmmwebcamp',
    name: 'DMM WEBCAMP',
    slug: 'dmm-webcamp',
    logo: { url: '/images/schools/dmmwebcamp.svg', width: 200, height: 56 },
    officialUrl: 'https://web-camp.io',
    affiliateUrl: 'https://example.com/aff/dmmwebcamp',
    catchphrase: '給付金活用で最大70%オフ、副業・転職どちらにも対応',
    description: 'DMM.comグループの安心感。給付金対象コースで費用を大幅削減しながら実践スキルを習得。',
    price: {
      basePrice: 580000,
      maxPrice: 690000,
      hasInstallment: true,
      installmentMonths: 24,
      installmentFeeRate: 0.12,
      subsidyAvailable: true,
    },
    curriculum: {
      languages: ['Ruby', 'JavaScript', 'Python', 'HTML', 'CSS'],
      frameworks: ['Ruby on Rails', 'React', 'Django'],
      hasPortfolio: true,
      weeklyHours: 40,
      totalHours: 480,
      hasMentor: true,
    },
    support: {
      jobSupport: true,
      jobSupportDetail: '転職サポート付き、求人紹介・書類添削・模擬面接あり',
      mentorResponse: '30分以内',
      communityExists: true,
      supportHours: '毎日10:00〜22:00',
    },
    results: {
      jobChangeRate: 95,
      satisfactionRate: 93,
      graduatesCount: 15000,
    },
    format: ['online'],
    purpose: ['career', 'side'],
    targetLevel: ['beginner', 'intermediate'],
    freeTrial: true,
    freeTrialDetail: '無料相談・体験レッスンあり',
    pros: [
      '給付金活用で実質費用を大幅削減可能',
      '副業・転職両方のコースがある',
      'DMMグループの安心感',
      '豊富なカリキュラム選択肢',
    ],
    cons: [
      'メンター対応がやや遅い',
      '給付金申請の手続きが複雑',
      'コミュニティが小規模',
    ],
    reviewScore: { curriculum: 4.0, price: 3.8, support: 4.0, userReview: 3.8 },
    reviewCount: 218,
    publishedAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2026-01-15T00:00:00.000Z',
  },
  {
    id: 'runteq',
    name: 'RUNTEQ',
    slug: 'runteq',
    logo: { url: '/images/schools/runteq.svg', width: 200, height: 56 },
    officialUrl: 'https://runteq.jp',
    affiliateUrl: 'https://example.com/aff/runteq',
    catchphrase: '現場レベルのスキルで即戦力エンジニアへ',
    description: 'Webエンジニアとして即戦力になれる実践的カリキュラム。チーム開発経験を積み、技術力で差をつける。',
    price: {
      basePrice: 550000,
      maxPrice: 550000,
      hasInstallment: true,
      installmentMonths: 24,
      installmentFeeRate: 0.12,
      subsidyAvailable: false,
    },
    curriculum: {
      languages: ['Ruby', 'JavaScript', 'HTML', 'CSS', 'SQL'],
      frameworks: ['Ruby on Rails', 'React'],
      hasPortfolio: true,
      weeklyHours: 20,
      totalHours: 900,
      hasMentor: true,
    },
    support: {
      jobSupport: true,
      jobSupportDetail: '転職サポートあり、現役エンジニアのメンタリング',
      mentorResponse: '1時間以内',
      communityExists: true,
      supportHours: '平日10:00〜22:00、土日10:00〜18:00',
    },
    results: {
      jobChangeRate: 90,
      satisfactionRate: 92,
      graduatesCount: 3000,
    },
    format: ['online'],
    purpose: ['career', 'skill'],
    targetLevel: ['beginner', 'intermediate'],
    freeTrial: true,
    freeTrialDetail: '無料カウンセリングあり',
    pros: [
      '実務レベルの高い技術力が身につく',
      'チーム開発でGitHub運用を習得',
      '現役エンジニアからのレビューが充実',
      '自分のペースで学習可能',
    ],
    cons: [
      '学習時間が長い（推奨900時間）',
      '補助金・給付金対象外',
      '転職保証なし',
      '転職率が他社より低め',
    ],
    reviewScore: { curriculum: 4.2, price: 4.0, support: 3.5, userReview: 3.6 },
    reviewCount: 156,
    publishedAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2026-01-15T00:00:00.000Z',
  },
];

export const SAMPLE_SCHOOLS: School[] = sampleSchools.map((s, i) => ({
  ...s,
  overallScore: calcOverallScore(s.reviewScore),
  rank: i + 1,
}));
